In [40]:
!pip install fastf1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: fastf1 in /usr/local/lib/python3.9/dist-packages (2.3.1)
Requirement already satisfied: pandas>=1.1.0 in /usr/local/lib/python3.9/dist-packages (from fastf1) (1.4.4)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from fastf1) (2.27.1)
Requirement already satisfied: signalr-client-aio in /usr/local/lib/python3.9/dist-packages (from fastf1) (0.0.1.6.2)
Requirement already satisfied: matplotlib>=3.3.3 in /usr/local/lib/python3.9/dist-packages (from fastf1) (3.7.1)
Requirement already satisfied: timple>=0.1.2 in /usr/local/lib/python3.9/dist-packages (from fastf1) (0.1.5)
Requirement already satisfied: requests-cache>=0.8.0 in /usr/local/lib/python3.9/dist-packages (from fastf1) (1.0.0)
Requirement already satisfied: thefuzz in /usr/local/lib/python3.9/dist-packages (from fastf1) (0.19.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (from fastf1) (1.10.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from fastf1) (1.22.4)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.3->fastf1) (4.39.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.3->fastf1) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.3->fastf1) (1.0.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.3->fastf1) (8.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.3->fastf1) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.3->fastf1) (1.4.4)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.3->fastf1) (5.12.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.3->fastf1) (23.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.3->fastf1) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.1.0->fastf1) (2022.7.1)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.9/dist-packages (from requests-cache>=0.8.0->fastf1) (22.2.0)
Requirement already satisfied: urllib3>=1.25.5 in /usr/local/lib/python3.9/dist-packages (from requests-cache>=0.8.0->fastf1) (1.26.15)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.9/dist-packages (from requests-cache>=0.8.0->fastf1) (22.2.0)
Requirement already satisfied: url-normalize>=1.4 in /usr/local/lib/python3.9/dist-packages (from requests-cache>=0.8.0->fastf1) (1.4.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests-cache>=0.8.0->fastf1) (3.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->fastf1) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->fastf1) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->fastf1) (3.4)
Requirement already satisfied: websockets>=4.0.1 in /usr/local/lib/python3.9/dist-packages (from signalr-client-aio->fastf1) (10.4)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.9/dist-packages (from cattrs>=22.2->requests-cache>=0.8.0->fastf1) (1.1.1)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/dist-packages (from importlib-resources>=3.2.0->matplotlib>=3.3.3->fastf1) (3.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.3->fastf1) (1.16.0)

In [41]:
import fastf1

In [42]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [43]:
%cd '/content/drive/MyDrive/Colab Notebooks/'

/content/drive/MyDrive/Colab Notebooks

In [44]:
fastf1.Cache.enable_cache('Cache')

In [45]:
year= 2023
gp = 'Saudi Arabia'
event = 'R'
session_race = fastf1.get_session(year, gp, event)
session_race.load()

In [46]:
session_race.results

,DriverNumber,BroadcastName,Abbreviation,TeamName,TeamColor,FirstName,LastName,FullName,Position,GridPosition,Q1,Q2,Q3,Time,Status,Points
11,11,S PEREZ,PER,Red Bull Racing,3671C6,Sergio,Perez,Sergio Perez,1.0,1.0,NaT,NaT,NaT,0 days 01:21:14.894000,Finished,25.0
1,1,M VERSTAPPEN,VER,Red Bull Racing,3671C6,Max,Verstappen,Max Verstappen,2.0,15.0,NaT,NaT,NaT,0 days 01:21:20.249000,Finished,19.0
14,14,F ALONSO,ALO,Aston Martin,358C75,Fernando,Alonso,Fernando Alonso,3.0,2.0,NaT,NaT,NaT,0 days 01:21:35.622000,Finished,15.0
63,63,G RUSSELL,RUS,Mercedes,6CD3BF,George,Russell,George Russell,4.0,3.0,NaT,NaT,NaT,0 days 01:21:40.760000,Finished,12.0
44,44,L HAMILTON,HAM,Mercedes,6CD3BF,Lewis,Hamilton,Lewis Hamilton,5.0,7.0,NaT,NaT,NaT,0 days 01:21:45.959000,Finished,10.0
55,55,C SAINZ,SAI,Ferrari,F91536,Carlos,Sainz,Carlos Sainz,6.0,4.0,NaT,NaT,NaT,0 days 01:21:50.770000,Finished,8.0
16,16,C LECLERC,LEC,Ferrari,F91536,Charles,Leclerc,Charles Leclerc,7.0,12.0,NaT,NaT,NaT,0 days 01:21:58.056000,Finished,6.0
31,31,E OCON,OCO,Alpine,2293D1,Esteban,Ocon,Esteban Ocon,8.0,6.0,NaT,NaT,NaT,0 days 01:22:07.726000,Finished,4.0
10,10,P GASLY,GAS,Alpine,2293D1,Pierre,Gasly,Pierre Gasly,9.0,9.0,NaT,NaT,NaT,0 days 01:22:09.641000,Finished,2.0
20,20,K MAGNUSSEN,MAG,Haas F1 Team,B6BABD,Kevin,Magnussen,Kevin Magnussen,10.0,13.0,NaT,NaT,NaT,0 days 01:22:19.720000,Finished,1.0
22,22,Y TSUNODA,TSU,AlphaTauri,5E8FAA,Yuki,Tsunoda,Yuki Tsunoda,11.0,16.0,NaT,NaT,NaT,0 days 01:22:22.388000,Finished,0.0
27,27,N HULKENBERG,HUL,Haas F1 Team,B6BABD,Nico,Hulkenberg,Nico Hulkenberg,12.0,10.0,NaT,NaT,NaT,0 days 01:22:25.482000,Finished,0.0
24,24,G ZHOU,ZHO,Alfa Romeo,C92D4B,Guanyu,Zhou,Guanyu Zhou,13.0,11.0,NaT,NaT,NaT,0 days 01:22:30.954000,Finished,0.0
21,21,N DE VRIES,DEV,AlphaTauri,5E8FAA,Nyck,De Vries,Nyck De Vries,14.0,18.0,NaT,NaT,NaT,0 days 01:22:32.372000,Finished,0.0
81,81,O PIASTRI,PIA,McLaren,F58020,Oscar,Piastri,Oscar Piastri,15.0,8.0,NaT,NaT,NaT,0 days 01:22:39.915000,Finished,0.0
2,2,L SARGEANT,SAR,Williams,37BEDD,Logan,Sargeant,Logan Sargeant,16.0,20.0,NaT,NaT,NaT,0 days 01:22:41.187000,Finished,0.0
4,4,L NORRIS,NOR,McLaren,F58020,Lando,Norris,Lando Norris,17.0,19.0,NaT,NaT,NaT,0 days 01:22:41.339000,Finished,0.0
77,77,V BOTTAS,BOT,Alfa Romeo,C92D4B,Valtteri,Bottas,Valtteri Bottas,18.0,14.0,NaT,NaT,NaT,NaT,+1 Lap,0.0
23,23,A ALBON,ALB,Williams,37BEDD,Alexander,Albon,Alexander Albon,19.0,17.0,NaT,NaT,NaT,NaT,Brakes,0.0
18,18,L STROLL,STR,Aston Martin,358C75,Lance,Stroll,Lance Stroll,20.0,5.0,NaT,NaT,NaT,NaT,Engine,0.0

In [47]:
year= 2022
gp = 'Singapore'
event = 'R'
session_race = fastf1.get_session(year, gp, event)
session_race.load()
session_race.results

,DriverNumber,BroadcastName,Abbreviation,TeamName,TeamColor,FirstName,LastName,FullName,Position,GridPosition,Q1,Q2,Q3,Time,Status,Points
11,11,S PEREZ,PER,Red Bull Racing,1e5bc6,Sergio,Perez,Sergio Perez,1.0,2.0,NaT,NaT,NaT,0 days 02:02:20.238000,Finished,25.0
16,16,C LECLERC,LEC,Ferrari,ed1c24,Charles,Leclerc,Charles Leclerc,2.0,1.0,NaT,NaT,NaT,0 days 02:02:22.833000,Finished,18.0
55,55,C SAINZ,SAI,Ferrari,ed1c24,Carlos,Sainz,Carlos Sainz,3.0,4.0,NaT,NaT,NaT,0 days 02:02:30.543000,Finished,15.0
4,4,L NORRIS,NOR,McLaren,f58020,Lando,Norris,Lando Norris,4.0,6.0,NaT,NaT,NaT,0 days 02:02:41.371000,Finished,12.0
3,3,D RICCIARDO,RIC,McLaren,f58020,Daniel,Ricciardo,Daniel Ricciardo,5.0,16.0,NaT,NaT,NaT,0 days 02:03:13.520000,Finished,10.0
18,18,L STROLL,STR,Aston Martin,2d826d,Lance,Stroll,Lance Stroll,6.0,11.0,NaT,NaT,NaT,0 days 02:03:16.568000,Finished,8.0
1,1,M VERSTAPPEN,VER,Red Bull Racing,1e5bc6,Max,Verstappen,Max Verstappen,7.0,8.0,NaT,NaT,NaT,0 days 02:03:19.063000,Finished,6.0
5,5,S VETTEL,VET,Aston Martin,2d826d,Sebastian,Vettel,Sebastian Vettel,8.0,13.0,NaT,NaT,NaT,0 days 02:03:20.270000,Finished,4.0
44,44,L HAMILTON,HAM,Mercedes,6cd3bf,Lewis,Hamilton,Lewis Hamilton,9.0,3.0,NaT,NaT,NaT,0 days 02:03:21.753000,Finished,2.0
10,10,P GASLY,GAS,AlphaTauri,4e7c9b,Pierre,Gasly,Pierre Gasly,10.0,7.0,NaT,NaT,NaT,0 days 02:03:29.814000,Finished,1.0
77,77,V BOTTAS,BOT,Alfa Romeo,b12039,Valtteri,Bottas,Valtteri Bottas,11.0,15.0,NaT,NaT,NaT,0 days 02:03:49.082000,Finished,0.0
20,20,K MAGNUSSEN,MAG,Haas F1 Team,b6babd,Kevin,Magnussen,Kevin Magnussen,12.0,9.0,NaT,NaT,NaT,0 days 02:03:52.848000,Finished,0.0
47,47,M SCHUMACHER,MSC,Haas F1 Team,b6babd,Mick,Schumacher,Mick Schumacher,13.0,12.0,NaT,NaT,NaT,NaT,+1 Lap,0.0
63,63,G RUSSELL,RUS,Mercedes,6cd3bf,George,Russell,George Russell,14.0,0.0,NaT,NaT,NaT,NaT,+2 Laps,0.0
22,22,Y TSUNODA,TSU,AlphaTauri,4e7c9b,Yuki,Tsunoda,Yuki Tsunoda,15.0,10.0,NaT,NaT,NaT,NaT,Accident,0.0
31,31,E OCON,OCO,Alpine,2293d1,Esteban,Ocon,Esteban Ocon,16.0,17.0,NaT,NaT,NaT,NaT,Engine,0.0
23,23,A ALBON,ALB,Williams,37bedd,Alexander,Albon,Alexander Albon,17.0,18.0,NaT,NaT,NaT,NaT,Collision damage,0.0
14,14,F ALONSO,ALO,Alpine,2293d1,Fernando,Alonso,Fernando Alonso,18.0,5.0,NaT,NaT,NaT,NaT,Engine,0.0
6,6,N LATIFI,LAT,Williams,37bedd,Nicholas,Latifi,Nicholas Latifi,19.0,19.0,NaT,NaT,NaT,NaT,Collision damage,0.0
24,24,G ZHOU,ZHO,Alfa Romeo,b12039,Guanyu,Zhou,Guanyu Zhou,20.0,14.0,NaT,NaT,NaT,NaT,Collision,0.0

In [49]:
year= 2023
gp = 'Saudi Arabia'
event = 'Q'
session_race = fastf1.get_session(year, gp, event)
session_race.load()
session_race.results

,DriverNumber,BroadcastName,Abbreviation,TeamName,TeamColor,FirstName,LastName,FullName,Position,GridPosition,Q1,Q2,Q3,Time,Status,Points
11,11,S PEREZ,PER,Red Bull Racing,3671C6,Sergio,Perez,Sergio Perez,1.0,0.0,0 days 00:01:29.244000,0 days 00:01:28.635000,0 days 00:01:28.265000,NaT,,0.0
16,16,C LECLERC,LEC,Ferrari,F91536,Charles,Leclerc,Charles Leclerc,2.0,0.0,0 days 00:01:29.376000,0 days 00:01:28.903000,0 days 00:01:28.420000,NaT,,0.0
14,14,F ALONSO,ALO,Aston Martin,358C75,Fernando,Alonso,Fernando Alonso,3.0,0.0,0 days 00:01:29.298000,0 days 00:01:28.757000,0 days 00:01:28.730000,NaT,,0.0
63,63,G RUSSELL,RUS,Mercedes,6CD3BF,George,Russell,George Russell,4.0,0.0,0 days 00:01:29.592000,0 days 00:01:29.132000,0 days 00:01:28.857000,NaT,,0.0
55,55,C SAINZ,SAI,Ferrari,F91536,Carlos,Sainz,Carlos Sainz,5.0,0.0,0 days 00:01:29.411000,0 days 00:01:28.957000,0 days 00:01:28.931000,NaT,,0.0
18,18,L STROLL,STR,Aston Martin,358C75,Lance,Stroll,Lance Stroll,6.0,0.0,0 days 00:01:29.335000,0 days 00:01:28.962000,0 days 00:01:28.945000,NaT,,0.0
31,31,E OCON,OCO,Alpine,2293D1,Esteban,Ocon,Esteban Ocon,7.0,0.0,0 days 00:01:29.707000,0 days 00:01:29.255000,0 days 00:01:29.078000,NaT,,0.0
44,44,L HAMILTON,HAM,Mercedes,6CD3BF,Lewis,Hamilton,Lewis Hamilton,8.0,0.0,0 days 00:01:29.689000,0 days 00:01:29.374000,0 days 00:01:29.223000,NaT,,0.0
81,81,O PIASTRI,PIA,McLaren,F58020,Oscar,Piastri,Oscar Piastri,9.0,0.0,0 days 00:01:29.706000,0 days 00:01:29.378000,0 days 00:01:29.243000,NaT,,0.0
10,10,P GASLY,GAS,Alpine,2293D1,Pierre,Gasly,Pierre Gasly,10.0,0.0,0 days 00:01:29.890000,0 days 00:01:29.411000,0 days 00:01:29.357000,NaT,,0.0
27,27,N HULKENBERG,HUL,Haas F1 Team,B6BABD,Nico,Hulkenberg,Nico Hulkenberg,11.0,0.0,0 days 00:01:29.547000,0 days 00:01:29.451000,NaT,NaT,,0.0
24,24,G ZHOU,ZHO,Alfa Romeo,C92D4B,Guanyu,Zhou,Guanyu Zhou,12.0,0.0,0 days 00:01:29.654000,0 days 00:01:29.461000,NaT,NaT,,0.0
20,20,K MAGNUSSEN,MAG,Haas F1 Team,B6BABD,Kevin,Magnussen,Kevin Magnussen,13.0,0.0,0 days 00:01:29.744000,0 days 00:01:29.634000,NaT,NaT,,0.0
77,77,V BOTTAS,BOT,Alfa Romeo,C92D4B,Valtteri,Bottas,Valtteri Bottas,14.0,0.0,0 days 00:01:29.929000,0 days 00:01:29.668000,NaT,NaT,,0.0
1,1,M VERSTAPPEN,VER,Red Bull Racing,3671C6,Max,Verstappen,Max Verstappen,15.0,0.0,0 days 00:01:28.761000,0 days 00:01:49.953000,NaT,NaT,,0.0
22,22,Y TSUNODA,TSU,AlphaTauri,5E8FAA,Yuki,Tsunoda,Yuki Tsunoda,16.0,0.0,0 days 00:01:29.939000,NaT,NaT,NaT,,0.0
23,23,A ALBON,ALB,Williams,37BEDD,Alexander,Albon,Alexander Albon,17.0,0.0,0 days 00:01:29.994000,NaT,NaT,NaT,,0.0
21,21,N DE VRIES,DEV,AlphaTauri,5E8FAA,Nyck,De Vries,Nyck De Vries,18.0,0.0,0 days 00:01:30.244000,NaT,NaT,NaT,,0.0
4,4,L NORRIS,NOR,McLaren,F58020,Lando,Norris,Lando Norris,19.0,0.0,0 days 00:01:30.447000,NaT,NaT,NaT,,0.0
2,2,L SARGEANT,SAR,Williams,37BEDD,Logan,Sargeant,Logan Sargeant,20.0,0.0,0 days 00:02:08.510000,NaT,NaT,NaT,,0.0